### PR TITLE
chore: Update CSS to improve footer image and text styling

### LINKED ISSUE #124: [BUG]: Footer text wrapping misaligned
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The address is being warped down at the wrong spots in the footer

image

### Expected Behavior

The text be split over lines such that no word is truncated or divided over two lines.
If this modification will lead to changes in the desktop view as well, please convey so in the PR.

### Steps To Reproduce

1. Open website in mobile view
2. Scroll to the footer

### Anything else?

_No response_

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### PR DESCRIPTION
**Pull request by caiodutra08**
## Motivation and Context

Fixes #124 

## Description
Added new styling rules to the main logo in larger screens, and in the text that was breaking letters when in mobile.
Now in mobile, the main logo is aligned in the middle with the text and the text now only breaks words not letters.

## How Has This Been Tested?
I tested with multiple dimensions. And actually doesn't affect any other areas.

## Screenshots (if appropriate):
Screenshot 2024-05-23 at 11 00 26
Screenshot 2024-05-23 at 11 01 33

## Types of Changes

- [x] Bug fix (non-breaking change that fixes an issue)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by adityaraute** [comment]
> Added new styling rules to the main logo in larger screens and in the text that was breaking letters when in mobile.
Not sure what you mean by this. 

> Now in mobile, the main logo is aligned in the middle with the text 
The logo is in the middle for the footer in mobile view on `main` branch. Not sure I understand this change either.

> and the text now only breaks words not letters.
This seems to be fixed, and is the only desirable change.

**Comment by caiodutra08** [comment]
Okay, I see what is your concern, I have only removed the padding so that it could be fully aligned in the middle.

**Review by adityaraute — APPROVED** [review]
Then it looks good to me

**Comment by caiodutra08** [comment]
Sorry, missclicked.

**Review by agriyakhetarpal — APPROVED** [review]

**Comment by adityaraute** [comment]
Thank you for your contribution!

**Pull request merged**
