### PR TITLE
Added links to the logo

### LINKED ISSUE #85: Redirect logo clicks to homepage
**Is your feature request related to a problem? Please describe.**
Clicking on the logo in the navbar currently does nothing

**Describe the solution you'd like**
When a user clicks on the logo from any page, they should be redirected to the homepage

- [ ] Would you like to work on this?

### PR DESCRIPTION
**Pull request by Bashamega**
## Motivation and Context

Fixes #85 

## Description

This PR should solve the #85 problem, it add an a tag around the image tag.

## How Has This Been Tested?

Yes

## Types of Changes

- [x ] Bug fix (non-breaking change that fixes an issue)
- [x ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by adityaraute** [comment]
Hi @Bashamega , 
As you are a repeat contributor, I request you to update the title and description of the PR appropriately. 
Following this I'll review the PR.

**Comment by Bashamega** [comment]
> Hi @Bashamega , As you are a repeat contributor, I request you to update the title and description of the PR appropriately. Following this I'll review the PR.

Sorry

**Comment by Bashamega** [comment]
> Looks great, but can you change those links to relative path? Just a better practice so that people working in `dev` phase can also use them.

sure

**Review by adityaraute — APPROVED** [review]
Looks perfect, thanks for your contribution

**Pull request merged**
