### PR TITLE
phone and email icon added

### PR DESCRIPTION
**Pull request by shyamtawli**
Issue #32 

Some code format has fixed automatically, I have tried to maintain it.

### CODE REVIEW

**Review by adityaraute — CHANGES_REQUESTED** [review]
Hi Shyam, sorry but the css file is still having those unwanted lint changes. This causes issues with other branches of the repo and forks that other contributors have created. Hope you understand.  HTML looks fine.

**Comment by shyamtawli** [comment]
Okay, fixed the CSS file,
Extension is doing that chances.

**Review by adityaraute — APPROVED** [review]
Looks good, now.

**Comment by adityaraute** [comment]
Thanks for the PR @shyamtawli 
Yeah it must be the prettier or other kind of extensions being used.

I'm trying to set a linting configuration for the entire repo. Do open a discussion or let me know about it if you're aware how to do it.

**Pull request merged**
