### PR TITLE
Contact section responsiveness and css clean-up

### PR DESCRIPTION
**Pull request by SidharthSreekumar**
## Motivation and Context

The contents of the contact section spilled over to the footer when the website was viewed on small devices.
Issue: [link](https://github.com/rbjks/rbjks.github.io/issues/123)

# Fixes

## Description

- Changed the contact section (.contact) height attribute to min-height. This made sure that it has 100vh height on large devices as well as the height increases if the content needs more space on smaller screens.
- Fixed indentation issues in contact.css, style.css, and contact.html.
- Moved contact section styling from style.css to contact.css and removed repeated CSS rules. 

## How Has This Been Tested?

Tested on different screen sizes using browser dev tools. Tested on Mozilla Firefox and Google Chrome.

## Screenshots (if appropriate):

image

## Types of Changes

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by adityaraute — CHANGES_REQUESTED** [review]
The UI looks great

I'm seeing lots of unnecessary changes in the CSS and HTML files with spaces and linting.

Please get rid of those, and the PR would be good to be merged.

**Comment by SidharthSreekumar** [comment]
Hi @adityaraute,

The contact.css has a different indentation when compared to other CSS files. Most CSS files use 2 space indentation where this one was using 4 space. Same holds true for style.css, where most of the code in that file is having 2 space indentation and from line 246, it changes to 4 space. The contact.html file was also having indentation inconsistencies which were corrected in the commit. Please let me know if you still want me to revert these changes.

**Comment by adityaraute** [comment]
I see your point about the CSS files @SidharthSreekumar that's a very good spot and I'm happy to merge those files now.

However, the changes in HTML file still deviates from the rest of the repo and I would like those changes to be reverted before merging the PR.

**Comment by SidharthSreekumar** [comment]
Hi @adityaraute, I was trying to revert the changes to the contact.html file. But the `lint-staged` is preventing me from doing a commit as it is mostly whitespace changes. Is there a workaround for this?

Moreover, I would like to add that `npm run fix` reapplies the changes that I have on my original PR.

**Comment by agriyakhetarpal** [comment]
>  Is there a workaround for this?

You can probably do something like `git commit -m "<your commit message>" --no-verify`

**Comment by SidharthSreekumar** [comment]
Hi @adityaraute,

I have reverted the indentation fixes for contact.html

**Review by adityaraute — APPROVED** [review]

**Comment by adityaraute** [comment]
Thanks for the contribution!

**Pull request merged**
