### PR TITLE
Contact page title 

### LINKED ISSUE #110: [BUG]: TYPO: Contact page title is activities
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The tab title for Contact page is incorrect

### Expected Behavior

Contact page tab title should read Contact

### Steps To Reproduce

1. Click on the Contact Us option in the navbar

### Anything else?

_No response_

### What browsers are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by Gokilp**
## Motivation and Context

Fixes #110 

## Types of Changes

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by adityaraute — CHANGES_REQUESTED** [review]
This change does not work as line 7 still has Activities as the new tab title.
Please edit that line with RBJKS as a prefix.
Please also get rid of the unnecessary empty lines added on line 5 and 19 of the new file.

**Comment by Gokilp** [comment]
I fixed issues please check PR request @adityaraute

**Review by adityaraute — APPROVED** [review]
Perfect

**Comment by adityaraute** [comment]
Thanks for the PR!
Look around for more issues to contribute to

**Comment by Gokilp** [comment]
Thank you

**Pull request merged**
