### PR TITLE
added a multi column footer

### PR DESCRIPTION
**Pull request by MaruthiKo**
This fixes the issue #3

### CODE REVIEW

**Comment by adityaraute** [comment]
Thank you for the PR. I'll try to review by the end of the week.

**Comment by adityaraute** [comment]
HI @MaruthiKo 

image


This is what I see on the portal. I really like the color combination you are using. 

I'd suggest getting rid of the first column.
For the second column, put some long `lorem ipsum` text for address, a dummy a number for phone, and a dummy email for email-id. That way it will be easier for me to test too.

**Comment by MaruthiKo** [comment]
> HI @MaruthiKo 
> 
> image
> 
> 
> This is what I see on the portal. I really like the color combination you are using. 
> 
> I'd suggest getting rid of the first column.
> For the second column, put some long `lorem ipsum` text for address, a dummy a number for phone, and a dummy email for email-id. That way it will be easier for me to test too.

Okay understood 👍

**Comment by MaruthiKo** [comment]
@adityaraute I have made the changes based on your suggestion. Have a look at them and let me know, if you need any other changes

**Review by adityaraute — COMMENTED** [review]
Footer looks good. But has conflicts with the existing branch.

**Comment by adityaraute** [comment]
Hi @MaruthiKo 

Since the fork you created is old, it is a few commits behind the current main branch.
image

Can you please pull the latest changes from rbjks:main on your repo, and then merge the changes? This will ensure that there are no conflicts.

**Comment by MaruthiKo** [comment]
Alright will do it

**Pull request closed without merging**
