### PR TITLE
Bashamega patch 1

### LINKED ISSUE #97: [FEATURE]: Add gitpod link to README
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Save the efforts for minor changes

### Proposed Solution

Include a direct link for GitPod development as is done in [this repo.](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io)

### Screenshots

_No response_

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this

_No response_

### PR DESCRIPTION
**Pull request by Bashamega**
## Motivation and Context

Fixes #97 

## Description

Added the Gitpod Edit image
## How Has This Been Tested?

I have click on the button from Microsoft Edge, and it worked
## Screenshots (if appropriate):
image

## Types of Changes

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Bashamega** [comment]
@adityaraute

**Review by adityaraute — COMMENTED** [review]
Is there a way to ensure this opens in a new tab/window instead?

**Comment by Bashamega** [comment]
> Is there a way to ensure this opens in a new tab/window instead?

I don't think so. I edited it to be opened with the atritbute `target="_blank"` but it is still opening in the same tab
@adityaraute

**Comment by adityaraute** [comment]
Noted, thanks for your contribution!

**Pull request merged**
