### PR TITLE
Navbar style

### PR DESCRIPTION
**Pull request by ArvindParekh**
#9 
Hi @adityaraute! I'm creating a draft pr here.
As the issue mentions, use theme colors in navbar links, the theme colors being Emerald - #22B9A8, Deep Saffron - #ff9933, and Desert Sand - #edc9af. I tried using them as colors for the links, but it doesn't pop out very as much as white or black does. 
So, I styled the navbar to get a bit more whitespace and I'm using the theme colors for the background or on hover.
This can be done in 4 ways:

Screenshot from 2023-02-25 18-38-41

Screenshot from 2023-02-25 18-38-54

Screenshot from 2023-02-25 18-42-02

Screenshot from 2023-02-25 18-42-11

I personally like the 4th one as it has a relaxing, cool feel.
The theme colors do not seem to match perfectly with the body background and that is why I wanted to get your views on this, regarding which one would you like on the website.
I could put the one you choose or go with some different colors for the navbar.
Thanks

### CODE REVIEW

**Comment by adityaraute** [comment]
Hi Arvind, thanks for the detailed examples.

I'm also in favour of the 4th option. But not sure what's happening here onhover. Is the cell getting a differnet colour, or is the text getting a colour or an underline or a change in size? I'd like you to experiment with all those options and choose the best one.

**Comment by ArvindParekh** [comment]
In the previous commit, the cell changed color on hover to Deep Saffron but it wasn't matching the background color of the navbar. The same goes for changing the text color to one of the theme colors. But I tried experimenting with underlining the text and a bit of scaling and I think this looks good. Let me know what you think about it. If you like this, I can go ahead and raise a pr for this.

https://user-images.githubusercontent.com/71211731/221400474-a6b8483a-9225-4ab7-a859-2e5532f5873f.mp4

**Comment by adityaraute** [comment]
This looks great. You can update the PR. I'm however waiting for #6 to be merged. Will merge your PR after that one.

**Comment by ArvindParekh** [comment]
Sure! No issue. 
Thanks Aditya!

**Pull request merged**
