### PR TITLE
brought the translate to hindi button to main page for smaller devices

### LINKED ISSUE #109: [FEATURE]:  Translate to Hindi link should be visible on mobile on the main page content
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Currently, the translate to Hindi link is inside the collapsed navbar.

### Proposed Solution

To improve the UX for mobile users, this link/option should be visible on the page content itself.
If possible, the website should also remember the settings from previous pages and carry it forward.

### Screenshots

_No response_

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this

_No response_

### PR DESCRIPTION
**Pull request by kripa-sindhu-007**
Screenshot 2024-06-13 170753

## Completed the task as expected

P.S:  Didn't used any text formatting to make any unnecessary changes :)

### CODE REVIEW

**Review by adityaraute — CHANGES_REQUESTED** [review]
Hi,

Thanks for reverting the linting changes

The changes are now visible on all pages.

However, if you observe the below screenshot, you'll notice that there are now two links for translation, one on the top nav, the other in the left, below the header.

Ideally, only the top nav one should be visible. Please fix this issue.
image

**Comment by kripa-sindhu-007** [comment]
Ohh Sorry I forgot to hide those in new PR. I have made those changes. Please verify now

**Comment by adityaraute** [comment]
image
The issue is still visible on the PR.

**Comment by kripa-sindhu-007** [comment]
how do you run it on local device the code. the last time I did it my way it made a lot of changes in file
after npm install whats next??

**Comment by kripa-sindhu-007** [comment]
Hopefully, It's gone now.....

Instead of display:none I used display:block to do things quickly :)

**Comment by adityaraute** [comment]
> Instead of display:none I used display:block to do things quickly :)

One should always maintain quality standards over everything else 😄

**Review by adityaraute — APPROVED** [review]
Looks fine now

**Comment by adityaraute** [comment]
Thank you for the PR

**Pull request merged**
