### PR TITLE
Footer Fixed by changing CSS

### LINKED ISSUE #67: Fix the footer in `contact` page
**Describe the bug**
The footer in the `contact` page is completely ruined

**To Reproduce**
1. Go to the website
2. Click on `Contact` in the navbar
3. Scroll down to the bottom of the page

**Expected behavior**
Footer should mimic the one on Homepage.

**Screenshots**
This is how the contact page footer is
image

This is how the Homepage footer is. This should be replicated above.
image

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome

### PR DESCRIPTION
**Pull request by miyannishar**
I commented on the line that assigned background color and min height of the footer section tag that was making the footer look weird.

## Motivation and Context

To fix the footer

Fixes #67

## Description
Changed CSS code

## How Has This Been Tested?
Live server running test

### CODE REVIEW

**Review by adityaraute — CHANGES_REQUESTED** [review]
Footer looks good. But two issues here,

1. The background of the body also seems to be removed. This shouldn't happen.
2. The contact modal is overflowing on the footer. Any way to fix this too?
image

**Comment by miyannishar** [comment]
Fixes: #67

**Review by adityaraute — APPROVED** [review]
You fixed the 2nd issue, but the 1st issue which was the more important one is still pending.

image


The background colour of the body is white, which it shouldn't be. It should be #edc9af that you've commented on line 80. Please fix this so I can merge the PR.

**Review by adityaraute — CHANGES_REQUESTED** [review]
You fixed the 2nd issue, but the 1st issue which was the more important one is still pending.

image


The background colour of the body is white, which it shouldn't be. It should be #edc9af that you've commented on line 80. Please fix this so I can merge the PR.

**Comment by miyannishar** [comment]
Fixes: #67

**Comment by adityaraute** [comment]
Thanks for your contribution!

Please feel free to browse around the repo and find more issues or PRs to work upon.

**Comment by miyannishar** [comment]
You are welcome! Feel free to poke me when you have related problems.

Regards,
Nishar Miya

**Pull request merged**
