### PR TITLE
Updated Favicon

### LINKED ISSUE #43: Update the Favicon for this website
**Is your feature request related to a problem? Please describe.**
I would love to bring to your notice that this site currently does not have any favicon and I feel adding the favicon would make it look and feel better

**Describe the solution you'd like**
I would like to use the logo of the website itself as the favicon for this site

**Describe alternatives you've considered**
Or may be we can create a favicon which relates with the said color theme and reference of the original logo

**Additional context**

### PR DESCRIPTION
**Pull request by SaiPreethamReddyy**
Fixes #43 
## Description

I have updated the favicon as per requested .

## Screenshots (if appropriate):
image

## Types of Changes

- [x ] New feature (non-breaking change that adds functionality)

### CODE REVIEW

**Review by agriyakhetarpal — APPROVED** [review]

**Review by adityaraute — APPROVED** [review]
Looks good. 
But any reason why you've persisted with the incorrect spelling of favicon?

**Comment by SaiPreethamReddyy** [comment]
> Looks good. But any reason why you've persisted with the incorrect spelling of favicon?
I have saved other symbol as favicon , so i have saved the pic with that name . Nothing more that than.

**Comment by adityaraute** [comment]
Okay I am merging this. Thanks for your contribution.
Feel free to look around the repo for more contributions.

**Comment by SaiPreethamReddyy** [comment]
Hey my PR that you merged on Favicon , i cant see that on website ! Is there any problem from my end ?

**Comment by adityaraute** [comment]
> Hey my PR that you merged on Favicon , i cant see that on website ! Is there any problem from my end ?

No. The website is fetching from the `development` branch. Your PR is merged on the `main` branch.

When the changes are moved from `main` to `development`, you will the see the favicon.

**Pull request merged**
