### PR TITLE
images json file

### LINKED ISSUE #51: Create a JSON-based image gallery
**Is your feature request related to a problem? Please describe.**
Currently, the image gallery is non-functional

**Describe the solution you'd like**
A grid-styled image gallery with captions that takes information from a JSON file stored on the repo.

**Additional context**
Use sample images and captions for the time-being.

### PR DESCRIPTION
**Pull request by OkelloSam21**
Fixes #51 

Changes proposed 

-
-
-

Test Methodology and Results

-
-
-

### CODE REVIEW

**Comment by adityaraute** [comment]
Hi Sam, thanks for the PR. It looks good but I don't see the image gallery being rendered on the html page. 
Can you please make sure it renders under the activities page? That would be great.

**Comment by adityaraute** [comment]
Hi @OkelloSam21 are you gonna render the gallery on the activities page?

**Comment by OkelloSam21** [comment]
Hi @adityaraute I will do it over the weekend I've been having my exams.

**Comment by adityaraute** [comment]
@OkelloSam21 Please provide an update on this issue, else I may have to unassign the issue

**Comment by OkelloSam21** [comment]
Hello,
Sorry I can't complete this issue. I recently changed my stack and am doing
*Android*
Just unassign me.

**Comment by adityaraute** [comment]
Closing the PR

**Pull request closed without merging**
