### PR TITLE
CSS: fix font color on contacts page 

### LINKED ISSUE #63: Incorrect Font Colour on `Contact` page
**Describe the bug**
Incorrect Font Colour on `Contact` page

**To Reproduce**
1. Go to the main branch
2. Click on 'Contact' on the homepage navbar

**Expected behavior**
Change the colour from black to white on the contact page navbar

**Screenshots**
image

### PR DESCRIPTION
**Pull request by ctrl07**
Screenshot 2023-12-28 124155

## Motivation and Context

Maintains consistent font color through out the website.

Fixes #63

## Description

Changed navbar text color from black to white.

## How Has This Been Tested?

 Using a browser. Screenshots attached. 

User live server extension in vs code. Checked if all navbar elements have same color.

## Types of Changes

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by adityaraute — CHANGES_REQUESTED** [review]
When I click the link, the font colour turns back to Black
image

This doesn't happen with other pages. Could you please investigate and fix this?

**Comment by ctrl07** [comment]
Screenshot 2023-12-28 135707

Hello Aditya the changes have been made accordingly.

**Review by adityaraute — APPROVED** [review]
Perfect!

**Comment by adityaraute** [comment]
Thanks for your contribution!
Feel free to check out more issues to contribute to on the repo.

**Pull request merged**
