### PR TITLE
Update index.html to update opening of social links in new tab

### LINKED ISSUE #44: Make tabs in the contact us part of the footer open in different tab
**Describe the bug**
I would like to highlight that the social media links given in the footer need to open in new tab to make the user experience feel better.
In the contact us part
image

**To Reproduce**
1. Go to the site https://rbjks.github.io/
2. Scroll down till the end of the website
3. See that all the social media links open in the same tab as the same tab where the website was open

**Expected behavior**

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Opera 
 - Version -

**Smartphone (please complete the following information):**
 - Device: Redmi
 - OS: MIUI 12
 - BrowserChrome
 - Version -

**Additional context**

### PR DESCRIPTION
**Pull request by tmsagarofficial**
Fixes #44 

Changes proposed 

image

Test Methodology and Results

Now all the links of social media pages open in new tabs.

### CODE REVIEW

**Review by adityaraute — APPROVED** [review]
Seems perfect to me

**Comment by tmsagarofficial** [comment]
thanks mate

**Comment by adityaraute** [comment]
No worries. Looking forward to more contributions from you on the repo.

**Comment by tmsagarofficial** [comment]
Sure bro i would also love to contribute on projects from their initial stages

**Pull request merged**
