### PR TITLE
Implemented a responsive grid gallery that gets images from a json file

### PR DESCRIPTION
**Pull request by cmmutale**
Fixes #

Changes Proposed

- Add new images.json File
- Added new gallery.html File to render the gallery
- Added new script to pull images from json file

Test Methodology and Results

- Used new gallery.html page to render the gallery.

### CODE REVIEW

**Comment by adityaraute** [comment]
Would have been better if you'd comment on the issue before starting to work on the PR

**Comment by cmmutale** [comment]
Apologies, this is my first time contributing, still learning the ropes. I'll do that for the others. Thanks!

**Review by adityaraute — CHANGES_REQUESTED** [review]
I like the way this is defined and rendered.
However, I wanted this to be a part of the `activities.html` page. Can you incorporate this code into that page?

**Comment by cmmutale** [comment]
Of course, working on that now

**Comment by cmmutale** [comment]
Would you want this on a new branch or the same **Image-gallery** branch I made?

**Comment by adityaraute** [comment]
> Apologies, this is my first time contributing, still learning the ropes. I'll do that for the others. Thanks!

No worries.

> Would you want this on a new branch or the same **Image-gallery** branch I made?

Same branch is fine too.

**Review by adityaraute — APPROVED** [review]
This looks great for now. Many thanks!

**Comment by adityaraute** [comment]
Looking forward to more contributions from you!

**Pull request merged**
