### PR TITLE
Image gallery

### PR DESCRIPTION
**Pull request by cmmutale**
Fixes # 51

Changes proposed 

- Re-styled the activities page height to fit gallery
-
-

Test Methodology and Results

- Added image gallery to activities.html page
-
-

### CODE REVIEW

**Comment by adityaraute** [comment]
We just merged those commits with #56 
Why did you create a new PR? Was it an accident?

**Comment by cmmutale** [comment]
It was an accident, sorry about that, I got confused with some instructions I was following. I decided to leave it before I mess things up more, still learning how contributing to oss is like.

**Comment by adityaraute** [comment]
> It was an accident, sorry about that, I got confused with some instructions I was following. I decided to leave it before I mess things up more, still learning how contributing to oss is like.

Oh don't worry about it. It can be confusing when you're new.
PRs are created between branches. So when you pushed commits to your Image Gallery branch, they also got updated in the PR. Hence, when I merged the PR with my `main` branch, those commits appeared on the main. There is no need to create multiple PRs for the same branch.


How did you discover this repo/issue BTW?

**Comment by cmmutale** [comment]
> > It was an accident, sorry about that, I got confused with some instructions I was following. I decided to leave it before I mess things up more, still learning how contributing to oss is like.
> 
> Oh don't worry about it. It can be confusing when you're new. PRs are created between branches. So when you pushed commits to your Image Gallery branch, they also got updated in the PR. Hence, when I merged the PR with my `main` branch, those commits appeared on the main. There is no need to create multiple PRs for the same branch.
> 
> How did you discover this repo/issue BTW?

Thanks for the Feedback! 

I saw it on discord.eddiehub.org, I just joined the discord because I am currently looking for a new developer role and I thought collaborating in the community with oss will give me better chances.

**Comment by adityaraute** [comment]
Oh great. I suspected that too. Engaging with the OSS community is a great step towards your developer journey.

**Comment by adityaraute** [comment]
I'll now close the PR as this is a duplicate of #56 which fixed the issue in question.

Once again, feel free to find other issues to contribute to @cmmutale

**Pull request closed without merging**
