### PR TITLE
Fixed Readability in the hero text of the landing page

### LINKED ISSUE #74: Fix the colors in the home page text for better readability
**Describe the bug**
The text on the home page has very little readability; hence, changing the colors might help do the job.

**To Reproduce**
1. Go to https://rbjks.github.io/
2. See that the text on the right of the image is a bit harder to read as the text is blended with the background color.

**Expected behavior**
A clear and readable text.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Opera - LVL5 (core: 105.0.4970.63)

I would love to work on this please assign this issue to me.

### PR DESCRIPTION
**Pull request by tmsagarofficial**
Made sure that the text present in the hero text  section i.e beside the image is more readable than before
## Motivation and Context
To increase readability as discussed in the following issue.

Fixes #74 

## Description
Changed the color of the test which was listed in the stylesheet which was linked to the index.html of this project.

## How Has This Been Tested?

I checked it on the local host and this is how it looks.

image

## Screenshots (if appropriate):
Before :
image

After:
image

## Types of Changes

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by agriyakhetarpal — APPROVED** [review]

**Comment by agriyakhetarpal** [comment]
Thanks @tmsagarofficial. Feel free to merge to deployment @adityaraute

**Comment by adityaraute** [comment]
> Thanks @tmsagarofficial. Feel free to merge to deployment @adityaraute

As stated in the linked issue, this is a duplicate. We already have fixed the font colour in our `main` branch

**Comment by agriyakhetarpal** [comment]
Ah I didn't notice that, no worries

**Comment by tmsagarofficial** [comment]
OKay not a problem .

**Comment by adityaraute** [comment]
Closed due to duplication issue

**Pull request closed without merging**
