### PR TITLE
changes to margins for mobile view fixes #115

### LINKED ISSUE #115: [BUG]: The introduction section is not designed properly and also the mobileview of that is not good can be changed.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Actually the introduction section of the website in home page is not looking good with inappropriate margins and padding.
Also the mobile view is looking very bad and it can broken with the column flex direction.

### Expected Behavior

The desktop view should be maintained with proper margin and padding.
The mobile view should also be improved with proper direction of the sections and the image and text should be one below other.

### Steps To Reproduce

1.Open the project
2.Preview the home page(index.html)
3.See the middle(introduction) section where there is image and text
4.See the middle(introduction) section in mobile view

### Anything else?

image

### What browsers are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by CampbellBrim**
Fixes #115 

## Description

Changes to margins to make responsive view fit better. 

## Screenshots (if appropriate):

before: 
image

after: 
image

### CODE REVIEW

**Review by adityaraute — APPROVED** [review]
This looks good now. And the commits are clean too.

**Comment by adityaraute** [comment]
Thanks for your contribution! Looking forward to more from you.

**Comment by CampbellBrim** [comment]
Thank you for your patience and I look forward to contributing more. I tried using the keyword "fixes", but I think it didn't work. How do I use the keyword correctly? It didn't give me an option to make it a keyword.

**Comment by agriyakhetarpal** [comment]
I think it works, but only when a collaborator or maintainer merges the PR. On the right side of this screen we can see the issue that was fixed through the changes in this PR

**Pull request merged**
