### PR TITLE
footer update

### LINKED ISSUE #124: [BUG]: Footer text wrapping misaligned
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The address is being warped down at the wrong spots in the footer

image

### Expected Behavior

The text be split over lines such that no word is truncated or divided over two lines.
If this modification will lead to changes in the desktop view as well, please convey so in the PR.

### Steps To Reproduce

1. Open website in mobile view
2. Scroll to the footer

### Anything else?

_No response_

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### PR DESCRIPTION
**Pull request by Bashamega**
Fixes #124 
image

### CODE REVIEW

**Review by adityaraute — CHANGES_REQUESTED** [review]
Looks good in desktop

image

Text not center aligned in mobile view though

Logo looks good.

**Comment by adityaraute** [comment]
Hi @Bashamega ,
Any updates on this one?

**Comment by Bashamega** [comment]
> Hi @Bashamega , Any updates on this one?

Sorry I have forgot. I will work on it

**Comment by adityaraute** [comment]
Okay, request review whenever it's done

**Review by adityaraute — CHANGES_REQUESTED** [review]
### Perfect in Mobile view
image

but....

### Messed up in Desktop view
image

**Comment by adityaraute** [comment]
Do you think putting those changes only under a media query would work?

**Comment by Bashamega** [comment]
> Hi @Bashamega Why was this PR closed?

I lost interest. Got busy in other jobs

**Pull request closed without merging**
