### PR TITLE
Home page changes

### PR DESCRIPTION
**Pull request by Barry2904**
All Hyperlink will open in the current browsing tab

### CODE REVIEW

**Comment by adityaraute** [comment]
Hi @Barry2904 I'd appreciate if you open an issue for this and then link the PR. We follow the Issue-> PR -> Review -> Merge pipeline for this repo.

**Review by adityaraute — CHANGES_REQUESTED** [review]
Request you to remove the repl files. Rest looks good to me.

**Comment by Barry2904** [comment]
Removed all repl files

**Review by shyamtawli — APPROVED** [review]
LGTM

**Review by adityaraute — APPROVED** [review]
Looks great

**Comment by adityaraute** [comment]
Thank you for the PR @Barry2904 , hoping for more contributions from you in the future.

@shyamtawli Thanks for the review. It helps a lot.

**Comment by Barry2904** [comment]
Sure, will make sure to contribute more

**Pull request merged**
