### PR TITLE
#1 added external website links to navbar elements

### PR DESCRIPTION
**Pull request by ArvindParekh**
Hi @adityaraute! 
I've added website URLs in the navbar's 'Activities' and 'Contact Us' elements. I've added the root route itself in the 'Home' element as I thought it should point to that only, and as for the last element, I have made no changes as it is primarily used to switch the website's language.
I hope you like it and please let me know if you want me to change anything or in case of any feedback, thanks!

### CODE REVIEW

**Review by adityaraute — CHANGES_REQUESTED** [review]
You are mistaken. The links should point to pages from the same website. Not external websites. The first one is fine but the rest are not.

**Comment by ArvindParekh** [comment]
Oh okay! Sorry about that, will change that right away.

**Comment by ArvindParekh** [comment]
I've updated the navbar links to point to pages within the same website using relative URLs assuming that the other pages would be present in the same directory. I've used the URLs '/activities.html' and '/contact.html' for the 'Activities' and 'Contact Us' links 
respectively.
Please let me know if there's anything else I can do to improve this pull request. Thanks!

**Review by adityaraute — APPROVED** [review]
This looks good. We may remove the target _blank property in the future though.

**Comment by adityaraute** [comment]
Great work @ArvindParekh !

**Comment by ArvindParekh** [comment]
> This looks good. We may remove the target _blank property in the future though.

Oh alright, no issues with that. I added it previously as I thought we need to redirect the users to some other websites.

**Comment by ArvindParekh** [comment]
> Great work @ArvindParekh !

Thank you very much for this opportunity Aditya! I'm glad to have worked on this:)

**Comment by adityaraute** [comment]
Would be looking forward for more contributions from you

**Pull request merged**
